<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-07T00:00:50 CST" name="Suite" finished-at="2025-01-07T00:00:56 CST" duration-ms="5854">
    <groups>
    </groups>
    <test started-at="2025-01-07T00:00:50 CST" name="Test" finished-at="2025-01-07T00:00:56 CST" duration-ms="5854">
      <class name="com.vamega.LoginTest">
        <test-method is-config="true" signature="preSetup()[pri:0, instance:com.vamega.LoginTest@2b71e916]" started-at="2025-01-07T00:00:50 CST" name="preSetup" finished-at="2025-01-07T00:00:50 CST" duration-ms="321" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preSetup -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.vamega.LoginTest@2b71e916]" started-at="2025-01-07T00:00:50 CST" name="setup" finished-at="2025-01-07T00:00:53 CST" duration-ms="2999" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyUserLoginWithCorrectCredentials(java.lang.String,java.lang.String)[pri:0, instance:com.vamega.LoginTest@2b71e916]" started-at="2025-01-07T00:00:54 CST" name="verifyUserLoginWithCorrectCredentials" finished-at="2025-01-07T00:00:56 CST" duration-ms="2212" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr605900]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pevevys]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [GTPL Bank Manage HomePage] but found [GTPL Bank Manager HomePage]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [GTPL Bank Manage HomePage] but found [GTPL Bank Manager HomePage]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.vamega.LoginTest.verifyUserLoginWithCorrectCredentials(LoginTest.java:27)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserLoginWithCorrectCredentials -->
        <test-method is-config="true" signature="postTestAction(org.testng.ITestResult)[pri:0, instance:com.vamega.LoginTest@2b71e916]" started-at="2025-01-07T00:00:56 CST" name="postTestAction" finished-at="2025-01-07T00:00:56 CST" duration-ms="251" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyUserLoginWithCorrectCredentials status=FAILURE method=LoginTest.verifyUserLoginWithCorrectCredentials(java.lang.String,java.lang.String)[pri:0, instance:com.vamega.LoginTest@2b71e916] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postTestAction -->
        <test-method is-config="true" signature="tearDowm()[pri:0, instance:com.vamega.LoginTest@2b71e916]" started-at="2025-01-07T00:00:56 CST" name="tearDowm" finished-at="2025-01-07T00:00:56 CST" duration-ms="326" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDowm -->
        <test-method is-config="true" signature="postTearDown()[pri:0, instance:com.vamega.LoginTest@2b71e916]" started-at="2025-01-07T00:00:56 CST" name="postTearDown" finished-at="2025-01-07T00:00:57 CST" duration-ms="552" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postTearDown -->
      </class> <!-- com.vamega.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
